name: Build & Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_URL }}

      - name: Build
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/myrepo/myapp
          TAG=${{ github.sha }}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest .

      - name: Push
        run: |
          IMAGE=${{ secrets.REGISTRY_URL }}/myrepo/myapp
          TAG=${{ github.sha }}
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
